SDS-1473

MET-NSCLC data to assign variant grouping to exon-14 skipping mutations

In [1]:
import pandas as pd
import re
import warnings
warnings.filterwarnings('ignore')

In [2]:
#read the data present in csv file
data = pd.read_csv("/Users/diwyanshu/Desktop/PROJECTS/PT360/EGFR/concerto_dev_c3_pt3602306_nsclc_biomarker.csv",
                   sep = ',', low_memory=False)

data.head()

,#,row_num,chai_patient_id,report_date,report_date_collected,biomarker_name_name,biomarker_name_code,biomarker_name_vocab,specimen_date,specimen_date_collected,...,molecular_variant,variant_classification_name,variant_classification_vocab,variant_grouping_code,variant_grouping_name,variant_grouping_vocab,biomarker_variant_origin_code,biomarker_variant_origin_name,biomarker_variant_origin_vocab,curation_indicator
0,1,76158,PT003866586,2020-08-22 00:00:00.000000,2020-08-22,MET,7029,HGNC,2020-08-13 00:00:00.000000,2020-08-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,2,76008,PT003879686,2020-06-10 00:00:00.000000,2020-06-10,MET,7029,HGNC,2020-06-04 00:00:00.000000,2020-06-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,3,77579,PT006202300,2021-12-21 00:00:00.000000,2021-12-21,MET,7029,HGNC,2021-12-02 00:00:00.000000,2021-12-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,4,77790,PT007720198,2022-04-25 00:00:00.000000,2022-04-25,MET,7029,HGNC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,5,78444,PT004903152,2021-02-15 00:00:00.000000,2021-02-15,MET,7029,HGNC,2021-02-05 00:00:00.000000,2021-02-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

MET Exon-14 Skipping Mutation
NCIt Code: C131179

In [3]:
#MET variant representative from PT360 dataset
#Defining MET exon 14 skipping mutation keywords and pattern for identification in molecular variants

keyword1 = 'MET exon 14 skipping'
keyword2 = 'MET exon 14 skipping mutation'

variant_patterns = [
    r'c\.3028G>C', r'c\.288-15_2892del20', r'c\.2888-10_2911del34', r'c\.2888-10C>G',
    r'c\.2888-12_2888-4delCTCTGTTTT',r'c\.2888-12_2909del',r'c\.2888-14_2888-4del',
    r'c\.2888-14_2888-4delCTCTCTGTTTT',r'c\.2888-14_2895del22',r'c\.2888-15_2888-2del14',
    r'c\.2888-15_2888-3del',r'c\.2888-15_2888-4del',r'c\.2888-15_2888-4delTCTCTCTGTTTT',
    r'c\.2888-15_2890delTCTCTCTGTTTTAAGATC',r'c\.2888-16_2888-4del',r'c\.2888-16_2891del',
    r'c\.2888-16_2891del;p.D963fs',r'c\.2888-16_2896del25',r'c\.2888-17_2888-16insAGAA',
    r'c\.2888-17_2888-1del',r'c\.2888-17_2905delTTTCTCTCTGTTTTAAGATCTGGGCAGTGAATTAG',
    r'c\.2888-18_2888-3del',r'c\.2888-18_2888-9delCTTTCTCTCT',r'c\.2888-19_2888-3del',
    r'c\.2888-19_2888del',r'c\.2888-19>2888-2delCTTTCTCTCTGTTTTAA',r'c\.2888-1G>A',
    r'c\.2888-2_2915del',r'c\.2888-20_2888-11del',r'c\.2888-20_2888-11delTTCTTTCTCT',
    r'c\.2888-20_2888-1del',r'c\.2888-20_2888-7>C',r'c\.2888-20_2939del',r'c\.2888-21_2888-5del',
    r'c\.2888-22_2888-2del',r'c\.2888-22_2891del',r'c\.2888-22_2891del;p.D963fs',r'c\.2888-24_2888-10del15',
    r'c\.2888-25_2888-3>ACT',r'c\.2888-27_2888-12del',r'c\.2888-28_2888-14del',r'c\.2888-28_2888-3>TTAG',
    r'c\.2888-28_2888-9del20',r'c\.2888-28_2891>G',r'c\.2888-29_2888-2delACAAGCTCTTTCTTTCTCTCTGTTTTAA',
    r'c\.2888-30_2888-15del16',r'c\.2888-30_2888-2del29',r'c\.2888-30_2888-3del28',r'c\.2888-30_2888-9del22',
    r'c\.2888-33_2888-1del',r'c\.2888-35_2888-17del',r'c\.2888-35_2888del',r'c\.2888-36_2888-12del25',
    r'c\.2888-4_2907del',r'c\.2888-4_2907del;p.D963fs',r'c\.2888-40_2888-17del24',
    r'c\.2888-40_2888-20delAGCCGTCTTTAACAAGCTCTT',r'c\.2888-40_2888-23del18',r'c\.2888-47_2888-24del24',
    r'c\.2888-5_2890TTAAGATC>A',r'c\.2888-5_2904del22',r'c\.2888-5_2905>AA',r'c\.2888-5_2944del62',
    r'c\.2888-52_2888-1del',r'c\.2888-61_2888-12>27',r'c\.2888-7_2920del',r'c\.2888A>G',r'c\.2888A>G;p.D963G',
    r'c\.2903_3028+67del',r'c\.2905_2940del',r'c\.2942-10_2958del27',r'c\.2942-14_2942-3del',
    r'c\.2942-14_2942-4del',r'c\.2942-14_2945del',r'c\.2942-15_2942-4del12',r'c\.2942-15_2943del',
    r'c\.2942-15_2946del20',r'c\.2942-16_2942-15insAG',r'c\.2942-16_2946delTTCTCTCTGTTTTAAGATCTG',
    r'c\.2942-17_2942-14delinsAGAAA',r'c\.2942-18_2942-5del ',r'c\.2942-18_2942-6del',r'c\.2942-18_2942-7del12',
    r'c\.2942-18_2942-8del ',r'c\.2942-19_2942-13delinsA',r'c\.2942-20_2945del24',r'c\.2942-20_294del26',
    r'c\.2942-21_2942--17delinsGAAA',r'c\.2942-27_2964del',r'c\.2942-28_2942-10del19',r'c\.2942-31_2942-4del',
    r'c\.2942-3A>G',r'c\.2942-40_2942-20del',r'c\.2942-42_2946del47',r'c\.2942-47_2949del',r'c\.2994_3028+1del',
    r'c\.3001_3021delGTAGACTACCGAGCTACTTTT;p.V1001_F1007del',
    r'c\.3003_3028+1delAGACTACCGAGCTACTTTTCCAGAAGGinsCTGTAGCTGCT',r'c\.3007T>C',r'c\.3007T>C;p.Y1003H',
    r'c\.3008A>G;p.Y1003C',r'c\.3010_3028+8del',r'c\.3012_3028+6del',r'c\.3017_3028+3del15',
    r'c\.3017_3028+5del17',r'c\.3017_3028+del27',r'c\.3017_3028delCTTTTCCAGAAGGT',r'c\.3018_3028+13del',
    r'c\.3018_3028+14del',r'c\.3018_3028+14del;p.F1007fs',r'c\.3018_3028+8del',r'c\.3018_3028+del',
    r'c\.3020_3028+24del',r'c\.3021_3028+14del22',r'c\.3021_3028+2delTCCAGAAGGT',r'c\.3024_3028delAGAAGGTATATT',
    r'c\.3025_3027GAA>Gfs',r'c\.3025_3028+13del17',r'c\.3026_3028+5delAAGGTATA',r'c\.3027_3028+13del',
    r'c\.3027_3028+13del;p.D1010fs',r'c\.3027_3028+1delAGG',r'c\.3027_3028+2delAGGTA',r'c\.3027_3028delAG',
    r'c\.3027_3028delAG;p.D1010fs*4',r'c\.3027_3028ins',r'c\.3028_3028+3delGGTA',r'c\.3028+1_3028+25del25',
    r'c\.3028+1_3028+2GT>AA',r'c\.3028+1_3028+3GTA>CTT',r'c\.3028+1_3028+9del',r'c\.3028+1G>A',r'c\.3028+1G>C',
    r'c\.3028+1G>T',r'c\.3028+2_3028+10delTATATTTCA',r'c\.3028+2_3028+4del',r'c\.3028+2T>A',r'c\.3028+2T>C',
    r'c\.3028+2T>G',r'c\.3028+3_3028+7del',r'c\.3028+3_3028+7delATATT',r'c\.3028+3A>G',r'c\.3028+3A>T',
    r'c\.3028G>A',r'c\.3028G>A;p.D1010N',r'c\.3028G>C',r'c\.3028G>C;p.D1010H',r'c\.3028G>T',
    r'c\.3028G>T;p.D1010Y',r'c\.3029C>T',r'c\.3029C>T;p.T1010I',r'c\.3058_3082+8delinsATA',
    r'c\.3067_3082+1delinsC',r'c\.3069_3081del',r'c\.3073_3082+2del',r'c\.3073_3082+4del14',
    r'c\.3076_3082+17del',r'c\.3076_3082+2del',r'c\.3076_3082+3del10',r'c\.3077_3082+9delCAGAAGGTATATTTC',
    r'c\.3081_3082+3del',r'c\.3082_3082+1del',r'c\.3082+1_3082+13del13',r'c\.3082+1delG',r'c\.3082+1G>A',
    r'c\.3082+1G>C',r'c\.3082+1G>T',r'c\.3082+2_3082+9del',r'c\.3082+2T>A',r'c\.3082+2T>C',
    r'c\.3082+3A>G',r'c\.3082+3A>T',r'c\.3082+6T>G',r'c\.3082C>G',r'c\.3082C>G;p.L1028V',r'c\.3082del',
    r'c\.3082G>A',r'c\.3082G>A;p.D1028N',r'c\.3082G>C',r'c\.3082G>C;p.D1028H',r'c\.3082G>T',
    r'c\.3082G>T;p.D1028Y',r'c\.3208G>C',r'c\.3208G>C;p.D1010H',r'c\.3280C>T;p.H1094Y',
    r'p\.D1010fs',r'p\.D1010fs*4',r'p\.D1010H',r'p\.D1010N',r'p\.D1010Y',r'p\.D1028H',r'p\.D1028N',r'p\.D1028Y',
    r'p\.D963fs',r'p\.D963G',r'p\.F1007fs',r'p\.L1028V',r'p\.T1010I',r'p\.Y1003H']

#these variant patterns are extracted from gn360 dataset and few literatures

In [4]:
#Filter applied: biomarker name = MET, test result name = poitive, equivocal and defined variant patterns
filtered_data = data[
    (data['biomarker_name_name'] == "MET") & 
    (data['test_result_name'].isin(['Positive', 'Equivocal'])) &
    (
        data['molecular_variant'].str.contains(keyword1, case=False, na=False) |
        data['molecular_variant'].str.contains(keyword2, case=False, na=False) |
        data['molecular_variant'].apply(lambda x: any(re.search(pattern, str(x)) for pattern in variant_patterns))
    )
]

#total molecular variants post filter for which variant grouping is required

filtered_data.groupby('molecular_variant').size().reset_index(name='count')

                           molecular_variant  count
0              MET Exon 14 Skipping Mutation      1
1                       MET exon 14 skipping     65
2               MET-MET;MET exon 14 skipping      1
3    c.288-15_2892del20;MET exon 14 skipping      1
4          c.2888-10C>G;MET exon 14 skipping      1
..                                       ...    ...
122                                 p.D1028H      1
123            p.D1028H;MET exon 14 skipping      1
124                                 p.D1028Y      1
125                                 p.T1010I      6
126                                 p.Y1003H      1

[127 rows x 2 columns]

In [5]:
#Check total sum
filtered_data.groupby('molecular_variant').size().reset_index(name='count').sum()

molecular_variant    MET Exon 14 Skipping MutationMET exon 14 skipp...
count                                                              297
dtype: object

In [6]:
# assign variant group MET exon 14 skipping to column variant_grouping_code, variant_grouping_name, and variant_grouping_vocab based on filtered data

filtered_data['variant_grouping_name'] = 'MET Exon 14 Skipping Mutation'

filtered_data['variant_grouping_code'] = 'C131179'

filtered_data['variant_grouping_vocab'] = 'NCIt'

#filtered_data.head()

In [7]:
#Check variant grouping sum
filtered_data.groupby(['variant_grouping_name', 'variant_grouping_code', 'variant_grouping_vocab']).size().reset_index(name='count')

,variant_grouping_name,variant_grouping_code,variant_grouping_vocab,count
0,MET Exon 14 Skipping Mutation,C131179,NCIt,297

In [8]:
#apply changes to the csv file

data.update(filtered_data)

In [9]:
# save the modified dataframe to the csv file

data.to_csv("MET_Q2_allData_Variant_Grouping.csv", index=False)